In [33]:
import numpy as np

# Часть 1
По максимуму буду использовать numpy, так как на бумаге писать огромное количество матриц с вычислениями невероятно трудозатратно.
## Задание 1.
### а) A(4,2), B(4,2)
AxB = (4,2)x(4,2) -> не определено, т.к. число столбцов в А не совпадает с числом строк в В.
BxA = (4,2)x(4,2) -> не определено, т.к. число столбцов в B не совпадает с числом строк в A.
### б) A(2,5), B(5,3)
AxB = (2,5)x(5,3) = (2,3). AxB определено, размерность результата (2,3)
BxA = (5,3)x(2,5) -> не определено, т.к. число столбцов в B не совпадает с числом строк в A.
### в) A(8,3), B(3,8)
AxB = (8,3)x(3,8) = (8,8). AxB определено, размерность результата (8,8)
BxA = (3,8)x(8,3) = (3,3). BxA определено, размерность результата (3,3)
### г) A(4,4), B(4,4)
AxB = (4,4)x(4,4) = (4,4). AxB определено, размерность результата (4,4)
BxA = (4,4)x(4,4) = (4,4). BxA определено, размерность результата (4,4)

## Задание 2.

In [8]:
A = np.array([[1,-2],[3, 0]])
B = np.array([[4,-1],[0, 5]])
print(f'Сумма матриц \n {A+B}')
print(f'Произведение матриц A*B\n {A.dot(B)}')
print(f'Произведение матриц B*A\n {B.dot(A)}')

Сумма матриц 
 [[ 5 -3]
 [ 3  5]]
Произведение матриц A*B
 [[  4 -11]
 [ 12  -3]]
Произведение матриц B*A
 [[ 1 -8]
 [15  0]]


## Задание 3.

In [11]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
С = np.array([[2,-4],[1,1]])
print(f'3A-2B+4C = \n {3*A-2*B+4*С}')

3A-2B+4C = 
 [[ 11  -5]
 [  9 -12]]


## Задание 4.

In [15]:
A = np.array([[4,1],[5,-2],[2,3]])
print(f'A = \n{A}\n\n A.T = \n{A.T}\n')
print(f'A*A.T = \n{A.dot(A.T)}\n')
print(f'A.T*A = \n{A.T.dot(A)}')

A = 
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

 A.T = 
[[ 4  5  2]
 [ 1 -2  3]]

A*A.T = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A.T*A = 
[[45  0]
 [ 0 14]]


## Задание 5.

In [1]:
A = [[4,1],[5,-2],[2,3]]
print(A)

[[4, 1], [5, -2], [2, 3]]


In [22]:

C = [[0] * 3 for _ in range(4)]
C[0][0] = 1
print(C)

[[1, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [31]:
def product(A, B):
    num_rows = len(A)
    num_columns = len(A[0])
    if num_columns != len(B):
        print('Произведение не определено')
        return
    C = [[0] * num_columns for _ in range(num_rows)]
    for i in range(num_rows):
        for j in range(num_columns):
            for k in range(num_columns):
                C[i][j] += A[i][k] * B[k][j]
    return C
A = [[1,-2],[3, 0]]
B = [[4,-1],[0, 5]]
print(product(A, B))
A = [[1,-2,1],[3, 0, 1]]
print(product(A, B))

[[4, -11], [12, -3]]
Произведение не определено
None


# Часть 2

## Задание 1
а) sin(x) * sin(x) - (-cos(x)) * (cos(x)) = sin(x)^2+cos(x)^2 = 1
б) Матрица треугольная. Определитель = 4*5*9 = 180
в) Определитель = 1*(5*9-6*8) -2*(4*9-6*7)+3*(4*8-5*7)=1*(-3) -2*(-6)+3*(-3)=-3-9+12=0
## Задание 2
а) det(A^2)=det(A*A)=det(A)*det(A)=4*4=16
б) det(A.T)=det(A)=4
в) det(2A) невозможно посчитать, так как неизвестен размер матрицы А.
## Задание 3
Вторая строка матрицы равна первой строке, умноженной на -2. Так как у матрицы есть линейно зависимые строки, то её определитель равен 0 и, следовательно, она вырождена.
## Задание 4
а) Вычтем из третьей строки матрицы первую и вторую. Третья строка обнулится - отбросим ее. В оставшейся матрице можно найти минор второго порядка.
Ответ: ранг = 2.
б) Все миноры четвертого порядка равны 0, существует минор 3-го порядка (в правом нижнем углу) не равный 0.
Ответ: ранг = 3.

In [38]:
A = [[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]]
print(np.linalg.matrix_rank(A))

3
